---
title: "Sites Data Structure"
author: "Víctor Granda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette the sites/plots data structure needed for the automated
calibration/validation of the medfate model is explained.

## Data files format

Files must be in `txt` format, with headers, without rownames, separated
by tabs (`"\t"`) and with point (`"."`) as decimal character.
Also, names of the files must start with the site/plot code.

## Needed files

Each site/plot data can be comprised of 9 files, some of them being optional:

- treeData
- shrubData (*optional*)
- seedData (*optional*)
- miscData
- meteoData
- soilData
- terrainData (*optional*)
- customParams (*optional*)
- measuredData

In the following sections each file will be described in detail using `FOO` as
site code

## treeData

> Name: FOO_treeData.txt  
  Location: Sites_data/FOO/

This data file must have 6 columns and the same number of rows as tree species
present in the site/plot:

Species | N | DBH | Height | Z50 | Z95
--------|---|-----|--------|-----|------
54 | 168 | 37.55 | 800 | 750 | 3000
68 | 384 | 14.60 | 660 | 750 | 3000

Variables:

  : **Species** A numeric code as found in the SpParams data from the `medfate` package
  : **N** Species density [trees/ha]
  : **DBH** Mean diameter at breast height for the species [cm]
  : **Height** Mean height for the species [cm]
  : **Z50** Depth in mm enclosing the 50% of the roots
  : **Z95** Depth in mm enclosing the 95% of the roots

## shrubData

> Name: FOO_shrubData.txt  
  Location: Sites_data/FOO/

This file is optional. If not supplied the shrub slot of the `forest` object
will be emtpy.  

File must have 4 columns and the same number of rows as shrub species present
in the site/plot:

Species | Cover | Height | Z
--------|-------|--------|----
64 | 3.75 | 30 | 2000
78 | 30.00 | 100 | 1000

Variables:

  : **Species** A numeric code as found in the SpParams data from the `medfate` package
  : **Cover** Percent cover of the species [%]
  : **Height** Mean height for the species [cm]
  : **Z** Depth in mm of the root system for the species

## seedData

> Name: FOO_seedData.txt  
  Location: Sites_data/FOO/

This file is optional. If not supplied the seedbank slot of the  `forest` object
will be empty.

File must have 2 columns and the same number of rows as species (tree + shrub)
present in the site/plot:

Species | Abundance
--------|----------
54 | 100
65 | 100
68 | 100
78 | 100

Variables:

  : **Species** A numeric code as found in the SpParams data from the `medfate` package
  : **Abundance** Abundance class

## miscData

> Name: FOO_miscData.txt  
  Location: Sites_data/FOO/

This file contains the single value elements of the forest object and must have
4 columns and one single row:

ID | patchsize | herbCover | herbHeight | Validation
---|-----------|-----------|------------|-------------
FOO | 10000 | 10 | 20 | global

Variables:

  : **ID** An identifier of the forest stand (a string)
  : **patchsize** The area of the forest stand in square meters
  : **herbCover** Percent cover of the herb layer
  : **herbHeight** Mean height in cm of the herb layer
  : **Validation** Validation to perform with this site, can be one of the
    following: "global", "global_transp" and "temperature"

## meteoData

> Name: FOO_meteoData.txt  
  Location: Sites_data/FOO/

This file contains the metereological data series, with as many rows as days
which must be modelled. It must have the following columns:

Variables:

  : **Date** Day date in the ISO format `YYYY-MM-DD`
  : **DOY** Day of year (Julian day)
  : **Precipitation** Precipitation (in mm)
  : **MeanTemperature** Mean temperature (in degrees Celsius)
  : **MinTemperature** Minimum temperature (in degrees Celsius)
  : **MaxTemperature** Maximum temperature (in degrees Celsius)
  : **MeanRelativeHumidity** Mean relative humidity (in percent)
  : **MinRelativeHumidity** Minimum relative humidity (in percent)
  : **MaxRelativeHumidity** Maximum relative humidity (in percent)
  : **Radiation** Solar radiation (in MJ/m2/day)
  : **WindSpeed** Wind speed (in m/s). If not available, this column can be left with NA values
  : **PET** Potential evapotranspiration (in mm)

## soilData

> Name: FOO_soilData.txt  
  Location: Sites_data/FOO/

This file must have 8 columns and as many rows as soil layers present in the
site/plot:

widths | clay | sand | macro | rfc | Gsoil | Ksoil | W | FC
-------|------|------|-------|-----|-------|-------|---|-----
300 | 25 | 25 | 0.1 | 30 | 0.5 | 0.05 | 1 | NA
700 | 25 | 25 | 0.1 | 60 | 0.5 | 0.05 | 1 | NA

Variables:

  : **widths** Width of soil layers in mm
  : **clay** Clay content percent for each soil layer
  : **sand** Sand content percent for each soil layer
  : **macro** Macroporosity for each layer
  : **rcf** Rock fragment content for each layer
  : **Gsoil** Gamma parameter for infiltration (same value for all layers)
  : **Ksoil** Kappa parameter for infiltration (same value for all layers)
  : **W** Initial water content of each soil layer in proportion (0-1)
  : **FC** Field capacity value in case of change from internal calculation

## terrainData

> Name: FOO_terrainData.txt  
  Location: Sites_data/FOO/

This file is optional if, **and only if**, complex mode will be not used. In
any other situation is mandatory.  

File must have 4 columns and one sigle row:

latitude | elevation | aspect | slope
---------|-----------|--------|-------
41.82592 | 100 | 0 | 0

Variables:

  : **latitude** Site/plot latitude in degrees (decimal format)
  : **elevation** Site/plot elevation in meters
  : **aspect** Site/plot aspect in degrees from North
  : **slope** Site/plot slope in degrees

## customParams

> Name: FOO_customParams.txt  
  Location: Sites_data/FOO/

This file is optional if no custom/optimized/measured parameters are provided
for the site.

It can contain any number of columns, and these must have the same names as in
the SpParamsMED dataset from `medfate` package or the `above` and `canopy` slots
of the swbInput object from the `medfate` package (see `medfate::forest2swbInput`
help function). Also it must have two columns, **SpIndex** and **Spcode**. The
first indicates the numeric code of the species as it appears in SpParamsMED
dataset and the second indicates the species code as used internally in `medfate`
(i.e. "T1_54"). As an example:

SpIndex | Spcode | xylem_kmax | Vmax298
--------|--------|------------|---------
54 | T1_54 | 0.4082 | 121.4565
68 | T2_68 | 0.1089 | 160.9927

## measuredData

> Name: FOO_measuredData.txt  
  Location: Sites_data/FOO/

This file **must have** the same number of rows as the meteoData file,
corresponding to the measured dates. After that the content depends on the kind
of validation the file is for.
For `global` and `global_transp` validations, it must have the measured values
for SWC (SWC for the first layer, SWC_2 for the second layer, and so on...) and
the values for transpiration (Eplanttot for total transpiration, and E_Tx_xx for
the different cohorts, being "Tx_xx" or "Sx_xx" the internal sp code used in
`medfate`). Also, there is an optional column "SWC_err" indicating the error
value for SWC content measure.
For example:

Date | SWC | SWC_err | SWC_2 | SWC_3 | Eplanttot | E_T1_54 | E_T2_64
-----|-----|---------|-------|-------|-----------|---------|---------
... | ... | ... | ... | ... | ... | ... | ... 

