---
title: "Report for `r params$code`"
author: "medfateTeam"
date: "`r Sys.time()`"
params:
  wd: ''
  code: ''
  transpMode: 'both'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = params$wd)
library(medfate)
library(MedfateValidation)
```

```{r data, message=FALSE}
# site/plot code
code <- params$code

# raw data
treeData <- load_treeData(code)
shrubData <- load_shrubData(code)
seedData <- load_seedData(code)
customParams <- load_customParams(code)
measuredData <- load_measuredData(code)
meteoData <- load_meteoData(code)
miscData <- load_miscData(code)
soilData <- load_soilData(code)
terrainData <- load_terrainData(code)

# model objects
forest_object <- buildForest(treeData, shrubData, seedData, miscData)
soil_object <- buildSoil(soilData)

# SpParams
data('SpParamsMED', package = 'medfate')

# SpParams modifications (if any)
sp_params <- SpParams_mod(SpParamsMED, customParams)
```


## *Simple* Model

```{r simple_model, eval=TRUE, message=FALSE}
# check if simple mode has to be performed
if (params$transpMode %in% c('simple', 'both')) {
  # control object
  control_obj <- medfate::defaultControl()
  control_obj$verbose <- FALSE
  control_obj$transpirationMode <- 'Simple'
  
  # input object
  simple_input <- medfate::forest2swbInput(forest_object, soil_object,
                                           sp_params, control_obj)
  
  # input modifications (if any)
  simple_input <- inputMod(simple_input, customParams)
  
  # model run
  res_simple <- medfate::swb(simple_input, soil_object, meteoData)
} else {
  # if simple mode is not performed, report about it
  cat('Simple model has not been selected to be performed')
}
```

```{r plot_simple, eval = TRUE, fig.height=8, fig.width=8}
# show the plot only if simple mode must be performed
if (params$transpMode %in% c('simple', 'both')) {
  # config layout
  par(mfrow = c(2,2))
  # P/PET plot
  plot(res_simple, yearAxis = TRUE)
  # ET plot
  plot(res_simple, type = 'ET', yearAxis = TRUE)
  # SWC plot
  plot(x = 1:nrow(meteoData),
       y = res_simple$SoilWaterBalance$W.1 * soil_object$Theta_FC[[1]],
       col = 'black', ylab = 'SWC', xlab = 'Days (absolute)')
  yts <- measuredData$SWC
  yse <- measuredData$SWC_err
  lines(x = 1:nrow(meteoData), y = yts, col = "red", lwd = 2)
  lines(x = 1:nrow(meteoData), y = yts + 1.96 * yse, col = "red", lwd = 1)
  lines(x = 1:nrow(meteoData), y = yts - 1.96 * yse, col = "red", lwd = 1)
  # Stress plot
  plot(res_simple, type = 'PlantStress', yearAxis = TRUE)
  # reset layout
  par(mfrow = c(1,1))
}
```

## *Complex* Model

```{r complex_model}
# check if complex mode has to be performed
if (params$transpMode %in% c('complex', 'both')) {
  # control object
  control_obj <- medfate::defaultControl()
  control_obj$verbose <- FALSE
  control_obj$transpirationMode <- 'Complex'
  
  # input object
  complex_input <- medfate::forest2swbInput(forest_object, soil_object,
                                            sp_params, control_obj)
  
  # input modifications (if any)
  complex_input <- inputMod(complex_input, customParams)
  
  # model run
  res_complex <- medfate::swb(complex_input, soil_object, meteoData,
                             terrainData$latitude, terrainData$elevation,
                             terrainData$slope, terrainData$aspect)
} else {
  # if simple mode is not performed, report about it
  cat('Complex model has not been selected to be performed')
}
```

```{r plot_complex, eval = TRUE, fig.height=8, fig.width=8}
# show the plot only if simple mode must be performed
if (params$transpMode %in% c('complex', 'both')) {
  # config layout
  par(mfrow = c(2,2))
  # P/PET plot
  plot(res_complex, yearAxis = TRUE)
  # ET plot
  plot(res_complex, type = 'ET', yearAxis = TRUE)
  # SWC plot
  plot(x = 1:nrow(meteoData),
       y = res_complex$SoilWaterBalance$W.1 * soil_object$Theta_FC[[1]],
       col = 'black', ylab = 'SWC', xlab = 'Days (absolute)')
  yts <- measuredData$SWC
  yse <- measuredData$SWC_err
  lines(x = 1:nrow(meteoData), y = yts, col = "red", lwd = 2)
  lines(x = 1:nrow(meteoData), y = yts + 1.96 * yse, col = "red", lwd = 1)
  lines(x = 1:nrow(meteoData), y = yts - 1.96 * yse, col = "red", lwd = 1)
  # Stress plot
  plot(res_complex, type = 'PlantStress', yearAxis = TRUE)
  # reset layout
  par(mfrow = c(1,1))
}
```

## Models comparision

TO DO:

+ r²
+ MAE
+ scatterplot simple vs complex

## Saving the txt res

```{r saving_txt_results}
if (params$transpMode %in% c('both')) {
  sp_names <- paste0('E_sp', simple_input$above$SP)
  saveRes(res_simple, res_complex,
          sp_names = sp_names, site_code = params$code)
} else {
  if (params$transpMode %in% c('simple')) {
    sp_names <- paste0('E_sp', simple_input$above$SP)
    saveRes(res_simple, sp_names = sp_names,
            site_code = params$code)
  } else {
    sp_names <- paste0('E_sp', complex_input$above$SP)
    saveRes(complex_res = res_complex, sp_names = sp_names,
            site_code = params$code)
  }
}
```

