#' Plotting the models results
#'
#' Function to generate models plots in order to inspect the results in a
#' visual way
#'
#' @param variable Character indicating the variable to visualize
#'
#' @param models List with the data frames with the results of the models as
#'   generated by \code{\link{saveRes}}
#'
#' @param soil Soil object used in the model
#'
#' @param measured_data Measured data dataframe
#'
#' @param mode Transpiration mode indicated in the models ('simple', 'complex' or 'both')
#'
#' @export

plot_res <- function(variable, models, soil, measured_data, mode) {

  # par
  par(mfcol = c(2,3))

  # SWC
  if (variable == 'SWC') {

    if (mode == 'both') {

      plot(models[['simple']][['Dates']],
           models[['simple']][['W.1']] * soil$Theta_FC[[1]],
           ylab = 'SWC', xlab = 'Date', type = 'n',
           main = 'Simple vs. Measured')
      lines(models[['simple']][['Dates']],
            models[['simple']][['W.1']] * soil$Theta_FC[[1]],
            col = 'blue')
      lines(models[['simple']][['Dates']],
            measured_data[['SWC']], col = 'red', lwd = 2)

      plot(models[['simple']][['W.1']] * soil$Theta_FC[[1]],
           measured_data[['SWC']], pch = 20, xlab = 'Simple', ylab = 'Measured')

      plot(models[['complex']][['Dates']],
           models[['complex']][['W.1']] * soil$Theta_FC[[1]],
           type = 'n', ylab = 'SWC', xlab = 'Date',
           main = 'Complex vs. Measured')
      lines(models[['complex']][['Dates']],
            models[['complex']][['W.1']] * soil$Theta_FC[[1]],
            col = 'green')
      lines(models[['complex']][['Dates']],
            measured_data[['SWC']], col = 'red', lwd = 2)

      plot(models[['complex']][['W.1']] * soil$Theta_FC[[1]],
           measured_data[['SWC']], pch = 20, xlab = 'Complex', ylab = 'Measured')

      plot(models[['simple']][['Dates']],
           models[['simple']][['W.1']] * soil$Theta_FC[[1]],
           col = 'blue', ylab = 'SWC', xlab = 'Date', type = 'n',
           main = 'Simple vs. Complex')
      lines(models[['complex']][['Dates']],
            models[['complex']][['W.1']] * soil$Theta_FC[[1]],
            col = 'green', lwd = 2)
      lines(models[['simple']][['Dates']],
            models[['simple']][['W.1']] * soil$Theta_FC[[1]],
            col = 'blue', lwd = 2)

      plot(models[['simple']][['W.1']] * soil$Theta_FC[[1]],
           models[['complex']][['W.1']] * soil$Theta_FC[[1]],
           pch = 20, xlab = 'Simple', ylab = 'Complex')
    }

    if (mode == 'simple') {
      plot(models[['simple']][['Dates']],
           models[['simple']][['W.1']] * soil$Theta_FC[[1]],
           ylab = 'SWC', xlab = 'Date', type = 'n',
           main = 'Simple vs. Measured')
      lines(models[['simple']][['Dates']],
            models[['simple']][['W.1']] * soil$Theta_FC[[1]],
            col = 'blue')
      lines(models[['simple']][['Dates']],
            measured_data[['SWC']], col = 'red', lwd = 2)

      plot(models[['simple']][['W.1']] * soil$Theta_FC[[1]],
           measured_data[['SWC']], pch = 20, xlab = 'Simple', ylab = 'Measured')
    }

    if (mode == 'complex') {
      plot(models[['complex']][['Dates']],
           models[['complex']][['W.1']] * soil$Theta_FC[[1]],
           type = 'n', ylab = 'SWC', xlab = 'Date',
           main = 'Complex vs. Measured')
      lines(models[['complex']][['Dates']],
            models[['complex']][['W.1']] * soil$Theta_FC[[1]],
            col = 'green')
      lines(models[['complex']][['Dates']],
            measured_data[['SWC']], col = 'red', lwd = 2)

      plot(models[['complex']][['W.1']] * soil$Theta_FC[[1]],
           measured_data[['SWC']], pch = 20, xlab = 'Complex', ylab = 'Measured')
    }
  }

  # E plant total
  if (variable == 'Eplanttot') {

    if (mode == 'both') {

      plot(models[['simple']][['Dates']],
           models[['simple']][['Eplanttot']],
           ylab = 'Eplanttot', xlab = 'Date', type = 'n',
           main = 'Simple vs. Measured')
      lines(models[['simple']][['Dates']],
            models[['simple']][['Eplanttot']],
            col = 'blue')
      lines(models[['simple']][['Dates']],
            measured_data[['Eplanttot']], col = 'red', lwd = 2)

      plot(models[['simple']][['Eplanttot']],
           measured_data[['Eplanttot']], pch = 20, xlab = 'Simple', ylab = 'Measured')

      plot(models[['complex']][['Dates']],
           models[['complex']][['Eplanttot']],
           type = 'n', ylab = 'Eplanttot', xlab = 'Date',
           main = 'Complex vs. Measured')
      lines(models[['complex']][['Dates']],
            models[['complex']][['Eplanttot']],
            col = 'green')
      lines(models[['complex']][['Dates']],
            measured_data[['Eplanttot']], col = 'red', lwd = 2)

      plot(models[['complex']][['Eplanttot']],
           measured_data[['Eplanttot']], pch = 20, xlab = 'Complex', ylab = 'Measured')

      plot(models[['simple']][['Dates']],
           models[['simple']][['Eplanttot']],
           col = 'blue', ylab = 'Eplanttot', xlab = 'Date', type = 'n',
           main = 'Simple vs. Complex')
      lines(models[['complex']][['Dates']],
            models[['complex']][['Eplanttot']],
            col = 'green', lwd = 2)
      lines(models[['simple']][['Dates']],
            models[['simple']][['Eplanttot']],
            col = 'blue', lwd = 2)

      plot(models[['simple']][['Eplanttot']],
           models[['complex']][['Eplanttot']],
           pch = 20, xlab = 'Simple', ylab = 'Complex')
    }

    if (mode == 'simple') {

      plot(models[['simple']][['Dates']],
           models[['simple']][['Eplanttot']],
           ylab = 'Eplanttot', xlab = 'Date', type = 'n',
           main = 'Simple vs. Measured')
      lines(models[['simple']][['Dates']],
            models[['simple']][['Eplanttot']],
            col = 'blue')
      lines(models[['simple']][['Dates']],
            measured_data[['Eplanttot']], col = 'red', lwd = 2)

      plot(models[['simple']][['Eplanttot']],
           measured_data[['Eplanttot']], pch = 20, xlab = 'Simple', ylab = 'Measured')
    }

    if (mode == 'complex') {

      plot(models[['complex']][['Dates']],
           models[['complex']][['Eplanttot']],
           type = 'n', ylab = 'Eplanttot', xlab = 'Date',
           main = 'Complex vs. Measured')
      lines(models[['complex']][['Dates']],
            models[['complex']][['Eplanttot']],
            col = 'green')
      lines(models[['complex']][['Dates']],
            measured_data[['Eplanttot']], col = 'red', lwd = 2)

      plot(models[['complex']][['Eplanttot']],
           measured_data[['Eplanttot']], pch = 20, xlab = 'Complex', ylab = 'Measured')
    }
  }

  # E by cohort
  if (variable == 'E_by_Cohort') {

    if (mode == 'both') {
      # get cohorts names
      coh_names <- as.character(
        na.omit(stringr::str_extract(names(models[['simple']]), '^E_.+'))
      )

      for (cohort in coh_names) {
        plot(models[['simple']][['Dates']],
             models[['simple']][[cohort]],
             ylab = cohort, xlab = 'Date', type = 'n',
             main = 'Simple vs. Measured')
        lines(models[['simple']][['Dates']],
              models[['simple']][[cohort]],
              col = 'blue')
        lines(models[['simple']][['Dates']],
              measured_data[[cohort]], col = 'red', lwd = 2)

        plot(models[['simple']][[cohort]],
             measured_data[[cohort]], pch = 20, xlab = 'Simple', ylab = 'Measured')

        plot(models[['complex']][['Dates']],
             models[['complex']][[cohort]],
             type = 'n', ylab = cohort, xlab = 'Date',
             main = 'Complex vs. Measured')
        lines(models[['complex']][['Dates']],
              models[['complex']][[cohort]],
              col = 'green')
        lines(models[['complex']][['Dates']],
              measured_data[[cohort]], col = 'red', lwd = 2)

        plot(models[['complex']][[cohort]],
             measured_data[[cohort]], pch = 20, xlab = 'Complex', ylab = 'Measured')

        plot(models[['simple']][['Dates']],
             models[['simple']][[cohort]],
             col = 'blue', ylab = cohort, xlab = 'Date', type = 'n',
             main = 'Simple vs. Complex')
        lines(models[['complex']][['Dates']],
              models[['complex']][[cohort]],
              col = 'green', lwd = 2)
        lines(models[['simple']][['Dates']],
              models[['simple']][[cohort]],
              col = 'blue', lwd = 2)

        plot(models[['simple']][[cohort]],
             models[['complex']][[cohort]],
             pch = 20, xlab = 'Simple', ylab = 'Complex')
      }
    }

    if (mode == 'simple') {
      # get cohorts names
      coh_names <- as.character(
        na.omit(stringr::str_extract(names(models[['simple']]), '^E_.+'))
      )

      for (cohort in coh_names) {
        plot(models[['simple']][['Dates']],
             models[['simple']][[cohort]],
             ylab = cohort, xlab = 'Date', type = 'n',
             main = 'Simple vs. Measured')
        lines(models[['simple']][['Dates']],
              models[['simple']][[cohort]],
              col = 'blue')
        lines(models[['simple']][['Dates']],
              measured_data[[cohort]], col = 'red', lwd = 2)

        plot(models[['simple']][[cohort]],
             measured_data[[cohort]], pch = 20, xlab = 'Simple', ylab = 'Measured')
      }
    }

    if (mode == 'complex') {
      # get cohorts names
      coh_names <- as.character(
        na.omit(stringr::str_extract(names(models[['complex']]), '^E_.+'))
      )

      for (cohort in coh_names) {
        plot(models[['complex']][['Dates']],
             models[['complex']][[cohort]],
             type = 'n', ylab = cohort, xlab = 'Date',
             main = 'Complex vs. Measured')
        lines(models[['complex']][['Dates']],
              models[['complex']][[cohort]],
              col = 'green')
        lines(models[['complex']][['Dates']],
              measured_data[[cohort]], col = 'red', lwd = 2)

        plot(models[['complex']][[cohort]],
             measured_data[[cohort]], pch = 20, xlab = 'Complex', ylab = 'Measured')
      }
    }
  }

  # reset layout
  par(mfrow = c(1,1))
}
